name: tests
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: vintzl <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_router: ^2.0.0-alpha+21
  angular_components: ^0.11.0
  http: ^0.12.0

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
